### ISSUE TITLE
"Remote ahead of" doesn't work

### ISSUE THREAD

**Issue by szpak** [mariuszs/informative_git_prompt#2]
informative_git_prompt for fish with an example configuration shows:
`... (topic/foo|✚3…1) $`
while version for bash and the previous port using Python:
`... (topic/foo ↑·2|✚3…1) $`

**Comment by mariuszs** [comment]
![zaznaczenie_019](https://f.cloud.github.com/assets/1623393/627217/d47fdef8-d00b-11e2-818d-3ce3866106c4.png)

Hmm, very strange

**Comment by szpak** [comment]
Hmm, I checked with two repos and thought it doesn't work at all. 

How to reproduce:

```
cd /tmp
git clone git://github.com/szpak/gradle-pitest-plugin.git
cd gradle-pitest-plugin/
touch foo.txt
git add foo.txt 
git commit -m "fake commit"
```

Expected result:
`foo@bar:/t/gradle-pitest-plugin (master ↑·1|✔) $`

Actual result:
`foo@bar:/t/gradle-pitest-plugin (master|✔) $`

It could be some problem with my configuration, but then I would expect to don't have a git prompt at all.

**Comment by mariuszs** [comment]
Thx, fixed
