### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Opalo** [mariuszs/informative_git_prompt#5]
This [line](https://github.com/mariuszs/informative_git_prompt/blob/master/example_config.fish#L8) is causing the following error:

> source: Error encountered while sourcing file '/Users/opal/.config/fish/informative_git_prompt.fish':
> source: No such file or directory

Is something misconfigured?

**Comment by mariuszs** [comment]
This project is outdated, prompt was merged into fishshell, so please check fishshell project how to configure informative prompt

https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_git_prompt.fish

>  informative    similar to verbose, but shows nothing when equal (fish only)

**Comment by Opalo** [comment]
Cool, thanks.

**Comment by mariuszs** [comment]
You can try my old configuration
http://mariuszs.github.io/blog/2013/informative_git_prompt.html
